In [2]:
import pandas as pd
from pandas import Series, DataFrame
import numpy as np

In [3]:
dframe = DataFrame(np.arange(0,16).reshape(4,4))

In [4]:
dframe

0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

In [7]:
blender = np.random.permutation(4)

In [8]:
blender

array([0, 3, 1, 2])

In [9]:
dframe.take(blender)

0   1   2   3
0   0   1   2   3
3  12  13  14  15
1   4   5   6   7
2   8   9  10  11

In [10]:
# permutation with replacement
box = np.array([1,2,3])

In [11]:
# size is how many time to take from the box
shaker = np.random.randint(0,len(box), size=10)
shaker

array([0, 1, 2, 1, 2, 2, 2, 1, 1, 0])

In [13]:
 # here hand grabs is like the results of taking numbered marbles from a box and putting it back for as many times
# specified in size on the shaker
hand_grabs = box.take(shaker)
hand_grabs

array([1, 2, 3, 2, 3, 3, 3, 2, 2, 1])

#### what is permutation??

in math, permutation of a set is, loosely speaking, an arrangement of its member into a sequence or linear order, or if the set is already ordered, a rearrangement of its elements. The word permutation also refers to the act or process of changing the linear order of an ordered set.